### PR TITLE
KDE KF6 update

### PR DESCRIPTION
**Pull request by travier**

### CODE REVIEW

**Comment by tsdgeos** [comment]
Why do you keep creating KF6 updates for things that are not KF6 based?

**Comment by travier** [comment]
The lists of which apps have been ported or not are not fully accurate so I'm going through all KDE Apps on Flathub and doing clean-ups and porting.

**Comment by travier** [comment]
As it's not KF6 yet, replaced by https://github.com/flathub/org.kde.kimagemapeditor/pull/11

**Comment by tsdgeos** [comment]
> The lists of which apps have been ported or not are not fully accurate so I'm going through all KDE Apps on Flathub and doing clean-ups and porting.

Which list are you using? https://community.kde.org/KDE_Gear/24.02_Release_notes is the real list, have you found any problem in that list?

**Comment by travier** [comment]
It includes both libraries and applications and I think it was missing some. I'll try looking at it again to update it.

**Comment by tsdgeos** [comment]
Do not update it without telling me because i'm 99.94% sure it is correct.

**Comment by travier** [comment]
OK, will ping you before touching it

**Pull request closed without merging**
